### ISSUE TITLE
Link in your blog post is incorrect

### ISSUE THREAD

**Issue by kbanks-krobotics** [darthrubens/tanks#3]
Blog post has a link of http://rubentd.com/blog/creating-a-multiplayer-game-with-node-js/github.com/rubentd/tanks

which needs to be trimmed down to just

github.com/rubentd/tanks

**Comment by z3t0** [comment]
This. I wanted to take a look at the code but the link was broken, google saved the day

**Comment by rubentd** [comment]
Thanks a lot for reporting this. I'll fix it right away.

**Comment by rubentd** [comment]
Done
